volumes:
  carecahub_pg_vol:
  carecahub_redis_vol:

networks:
  carecahub_net:
    name: carecahub_net

services:
  carecahub_db:
    container_name: carecahub_db
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: carecahub
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - carecahub_net
    volumes:
      - carecahub_pg_vol:/var/lib/postgresql
  carecahub_redis:
    container_name: carecahub_redis
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - carecahub_net
    volumes:
      - carecahub_redis_vol:/data
